// <auto-generated />

#nullable disable

namespace systemeGAB.DataClass.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("systemeGAB.DataClass.EntityModels.CarteBancaire", b =>
                {
                    b.Property<int>("idCarte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCarte"), 1L, 1);

                    b.Property<int>("codePin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCompte")
                        .HasColumnType("int");

                    b.Property<int>("numeroCarte")
                        .HasColumnType("int");

                    b.Property<string>("statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCarte");

                    b.ToTable("carteBancaire");
                });

            modelBuilder.Entity("systemeGAB.DataClass.EntityModels.Client", b =>
                {
                    b.Property<int>("idClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idClient"), 1L, 1);

                    b.Property<string>("adresseClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenomClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephoneClient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idClient");

                    b.ToTable("client");
                });

            modelBuilder.Entity("systemeGAB.DataClass.EntityModels.CompteBancaire", b =>
                {
                    b.Property<int>("idCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCompte"), 1L, 1);

                    b.Property<DateTime?>("dateOuverture")
                        .HasColumnType("datetime2");

                    b.Property<int>("idClient")
                        .HasColumnType("int");

                    b.Property<string>("numeroCompte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("solde")
                        .HasColumnType("float");

                    b.Property<string>("typeCompte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCompte");

                    b.ToTable("compteBancaire");
                });

            modelBuilder.Entity("systemeGAB.DataClass.EntityModels.Transaction", b =>
                {
                    b.Property<int>("idTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTransaction"), 1L, 1);

                    b.Property<DateTime?>("dateHeure")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCompte")
                        .HasColumnType("int");

                    b.Property<double?>("montant")
                        .HasColumnType("float");

                    b.Property<string>("statut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTransaction");

                    b.ToTable("transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
